<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Loan Account Creation</name>
   <tag></tag>
   <elementGuidId>0d83dec3-f38e-43cd-b3ba-d681490adab9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e_ZwZkZGVmZQL0BGRmZQNjZwVjZQL0Zt==']/button/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.lms</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4ccadc6f-693b-4a17-ba48-0b7e4d97d4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms</value>
      <webElementGuid>6bc5ccfc-4851-4c0c-8941-148f8a47c1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Loan Account Creation</value>
      <webElementGuid>da1a7d59-3700-45e5-bb7e-de4526b4967f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e_ZwZkZGVmZQL0BGRmZQNjZwVjZQL0Zt==&quot;)/button[@class=&quot;lm&quot;]/div[@class=&quot;lms&quot;]</value>
      <webElementGuid>db65d9d3-c600-45ab-ab15-817b3dce000b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Inbox/iframe_Undo_ifinbox</value>
      <webElementGuid>e9683dd1-d2a5-4c8b-8b42-e602ac8b4dde</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e_ZwZkZGVmZQL0BGRmZQNjZwVjZQL0Zt==']/button/div[2]</value>
      <webElementGuid>1c9f5038-7dc3-49e0-b8c9-f71d3bc54936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev@cba.net'])[1]/following::div[1]</value>
      <webElementGuid>97f1c3ee-d179-44f5-b573-46c18ef5bae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='today'])[1]/following::div[4]</value>
      <webElementGuid>63015054-9c4d-4ea5-aaad-b849905b425a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday'])[1]/preceding::div[1]</value>
      <webElementGuid>921a29e5-595e-4870-9e59-2d8c887411fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev@cba.net'])[2]/preceding::div[3]</value>
      <webElementGuid>dbf6e22f-72d9-4ea6-9ffd-c78c462b4b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Loan Account Creation']/parent::*</value>
      <webElementGuid>f2179897-c146-4251-80f2-8ad8ad97922e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div[2]</value>
      <webElementGuid>90dad386-3e7b-4299-a36b-ce4733f4f5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Loan Account Creation' or . = 'Loan Account Creation')]</value>
      <webElementGuid>43be848a-82cc-4e3f-9c17-324ddfff9316</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
