<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Overview</name>
   <tag></tag>
   <elementGuidId>9eb55009-92a4-450b-844c-1bda09865b10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payments > li > a.justify-content-between</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='payments']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1c56ad6d-1938-40c2-b521-89ff5b3ce485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/payments/overview</value>
      <webElementGuid>011f827c-ec4e-4ffa-892f-573690613d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-content-between</value>
      <webElementGuid>d7b5238f-2280-4053-a673-e0c6ce8f6766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Overview</value>
      <webElementGuid>5827c075-c064-401e-8d35-88b43c7219e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payments&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]</value>
      <webElementGuid>b67d4034-735a-4992-b411-7ae056abf4db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='payments']/li/a</value>
      <webElementGuid>fdac0377-1f50-4a50-a0df-a239bb5cbff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payments'])[1]/following::a[1]</value>
      <webElementGuid>9f3b8858-6913-4805-ab87-e9f007422323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Documentation'])[1]/following::a[2]</value>
      <webElementGuid>b2fa84e7-06fa-4673-a259-e817b3c104c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/preceding::a[1]</value>
      <webElementGuid>4dc5df88-524a-4c40-bce7-0c00756fba5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/payments/overview')]</value>
      <webElementGuid>c7f7d63a-2787-4852-937c-23361a41891d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[2]/li/a</value>
      <webElementGuid>a4891ba6-e0bd-4bea-a89f-7d16d6364c6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payments/overview' and (text() = 'Overview' or . = 'Overview')]</value>
      <webElementGuid>b31c1d76-989f-4000-95c2-7b2402846543</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
