<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_See All Customers</name>
   <tag></tag>
   <elementGuidId>4f77ff70-afd6-4718-bd33-6557689f8d6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.d-flex.align-items-center.heading-3.gap-2.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9c31cafc-8be2-4e03-ab7e-eac41d30bc7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/payments/customers</value>
      <webElementGuid>32dab2b8-10e7-4123-b9c9-ea15aac7d110</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex align-items-center heading-3 gap-2 primary</value>
      <webElementGuid>f0208128-0ecc-4ad6-a051-5b0e4eacc81b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> See All Customers </value>
      <webElementGuid>a2ffa7c7-2e41-4db3-be01-c29e74118a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;row g-4&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;d-flex flex-column stat--container border h-100&quot;]/div[@class=&quot;d-flex flex-column flex-sm-row gap-4 justify-content-between border-bottom pb-4 mb-4&quot;]/a[@class=&quot;d-flex align-items-center heading-3 gap-2 primary&quot;]</value>
      <webElementGuid>0720f5ba-8fde-4f01-8435-f4b9b8083be3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div/div/div/a</value>
      <webElementGuid>3f008838-7859-422e-9c83-fe4d9d466556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'See All Customers')]</value>
      <webElementGuid>19e068f4-aaf4-4cf2-a9c4-3256b5c0a7ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL CUSTOMER - 67'])[1]/following::a[1]</value>
      <webElementGuid>5ea11e53-7fb7-4d66-b009-48f18cf4565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Polaris Bank Limited'])[1]/following::a[1]</value>
      <webElementGuid>e379abf1-ce2a-426b-9feb-d1a5f8d51947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[1]</value>
      <webElementGuid>237efe1a-07c5-40b4-aa72-7ca9709ef326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[2]/preceding::a[1]</value>
      <webElementGuid>8d4b7c17-92bb-4198-a374-7465d69fe720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='See All Customers']/parent::*</value>
      <webElementGuid>8b2691df-a5c9-4817-8db7-fd0da6a87f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/payments/customers')])[2]</value>
      <webElementGuid>d7b09bcb-9e3d-4387-b7ce-38a72d0c44e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>3d0edaee-f2b0-4fdc-891e-8446a6765b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/payments/customers' and (text() = ' See All Customers ' or . = ' See All Customers ')]</value>
      <webElementGuid>6198edd6-6933-45d2-89ef-371ec545f547</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
