<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>afbc1128-a132-4a7c-9954-a502c8419002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn--lg.btn--primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2a46dfef-baa4-49e4-8995-f2f675071c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>3ed5c563-b792-4883-af84-a128e8217eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a90ea6e1-f0aa-4d8c-8f00-b413c5a789be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>bf4bc450-543d-4168-96cf-e41d9bb2adea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>06fc142d-5bf9-480d-9d00-5f9e50dc138d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>232f3d5f-5aa5-4ec8-966c-35e64f71b550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>26fbfb9a-a18b-45bf-a118-c4422b2952a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>78dddd6c-69c3-4cd1-9538-74b57627bab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>6a466b3e-6e85-4873-8083-3ca0a3e8423e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>4d060ffb-5967-426a-a348-4f09a3f09ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b393cc0e-6fb0-4061-8a64-8dc713862d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>5d17d16c-39f3-4534-8b6d-fcab90331c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0f6180e5-6672-4730-9bf5-412cbf9afbf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>fc56023a-6370-445e-a33d-9c6b00f36018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>21d57a46-4940-40ed-a916-5d8c6bf64327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>04d9fd58-88de-4c6d-81a5-becca2b02b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>898446e2-9156-492a-9b4e-cb6d37f8fe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>78d55f47-baf4-4eb8-9f99-408c9e9c2af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>823b7f28-4b8e-45c9-93c4-404afb757659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>6153f8d3-f441-48bf-88f3-5a9f5448356b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3026e819-bce8-4ac9-b0ae-132db068a5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>32b80047-37e4-427c-b338-68ed062c8c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>cea1bbdc-3bf4-4903-97f6-bddadc014424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>3354edf4-2ac8-4990-871d-e3d7329920dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>d8f4989b-b097-405e-ac19-df9cd71135a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fc30351a-545e-4d07-bd95-01f4b13a726b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>895230ae-e24c-4bda-b387-1f524b66e3d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>60e2e4bf-9cac-4493-9048-6c2424b0353b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>7ae422e5-52c5-48a4-8621-270bda2bb807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>1bdffaea-0e53-469f-b98f-c8172082e6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>89d33631-6200-4b60-91c8-222c999de059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>ab62a708-0d26-4de4-aefb-5a51397c3f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>56333b88-dea3-4b90-9d36-398f59494e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c88475b4-d5c3-4783-bde9-571ffcdce516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>052c6dc0-fb19-41b7-9e6f-24aeffb9db01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ece87c21-7419-42b4-a242-b03489045c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--lg btn--primary</value>
      <webElementGuid>dedb6be0-6a50-4c78-aacf-c9e6c6609c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>505f2aba-1abb-4a19-8a90-71f5351a4aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>c2dba6f1-91a5-407f-a06c-aef4bb8e4d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;auth-bg&quot;]/div[@class=&quot;d-flex align-items-center justify-content-center w-100 min-vh-100 py-5&quot;]/div[@class=&quot;col-11 col-md-7 col-xl-4&quot;]/div[@class=&quot;login-form p-5&quot;]/form[@class=&quot;mt-5&quot;]/div[@class=&quot;col-12&quot;]/button[@class=&quot;btn btn--lg btn--primary&quot;]</value>
      <webElementGuid>702724aa-405f-49c5-8ed8-c66087ac15a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>400812f0-17b9-4882-b457-ad6db5f974f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/form/div[4]/button</value>
      <webElementGuid>e2172232-5c61-468e-8fb0-f2b55f39ea23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Up'])[1]/following::button[1]</value>
      <webElementGuid>6d60608b-eb19-4178-a83e-56f07262f7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to website'])[1]/preceding::button[1]</value>
      <webElementGuid>299a589c-9e14-4056-a328-afd44fcd58ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>5dd1f461-f2f1-49d6-bd90-f9d2d53acba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>314c389d-87dc-4dfa-b7a6-60d0dfa04089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>7e9fcf0c-1375-4387-b685-73ae8d6ed17a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
