<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_coreapp_2</name>
   <tag></tag>
   <elementGuidId>f178dacb-7280-4355-a755-32a40d39a748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'option__list' and (text() = 'coreapp' or . = 'coreapp')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[text()=&quot;coreapp&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>df712797-270f-4bef-85bb-62bd43d6d6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option__list</value>
      <webElementGuid>2de9c08d-7f77-4998-9ad6-612d290de95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>coreapp</value>
      <webElementGuid>5aa0c98b-0dc0-40f2-8b7b-73c154139467</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;items&quot;]/div[@class=&quot;options&quot;]/div[@class=&quot;option__list&quot;]</value>
      <webElementGuid>e9ea29df-1149-480d-b931-5de3a945f078</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouch-notification-app'])[2]/following::div[1]</value>
      <webElementGuid>8d5a644f-bfd9-47ba-a569-f72fc4d09471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouchapp2'])[2]/following::div[2]</value>
      <webElementGuid>a5a2f5fd-12ca-4ccc-afc9-3a84605c0a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all-identity'])[2]/preceding::div[1]</value>
      <webElementGuid>965ecc9a-86a2-481e-80e6-275e13b81b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev-test'])[2]/preceding::div[2]</value>
      <webElementGuid>b76b1acc-a7b3-4d73-9aef-5abc0b709713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]</value>
      <webElementGuid>590fc896-b393-4937-b28d-32ede2eb2cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'coreapp' or . = 'coreapp')]</value>
      <webElementGuid>3afa8b32-1889-43f4-b331-897623539b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouch-notification-app'])[1]/following::div[1]</value>
      <webElementGuid>30f5c489-5aea-43a5-9763-341c6cf93604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouchapp2'])[1]/following::div[2]</value>
      <webElementGuid>4680929a-a0f1-4e5d-8386-89bcb9f476a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all-identity'])[1]/preceding::div[1]</value>
      <webElementGuid>4623f13f-dedb-4b00-b7f0-e728b16c1140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev-test'])[1]/preceding::div[2]</value>
      <webElementGuid>27355434-9f2c-4f60-b121-76c83e741b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='coreapp']/parent::*</value>
      <webElementGuid>bf2af8b8-a64b-436c-a9d5-e4a59c2b5428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
      <webElementGuid>ecdba42a-325b-4218-b8ac-8703e688ae59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
