<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Verifications</name>
   <tag></tag>
   <elementGuidId>a1bdb6aa-57c2-4389-89e0-7f97bc06e631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='verifications-container']/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verifications-container > a.justify-content-between > div.d-flex.align-items-center > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e181392d-46ef-4c34-82e0-d9a0de463340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>70919b15-833a-4746-9cc5-d9ea297e230d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>d6fa19ab-e90f-4401-aa0b-bfe98cea6d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc6a098e-6269-421c-905e-ef6fa94250f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>4f8034b1-42f4-4a7d-a06f-b0ebb701066b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>e879132a-263d-4a2d-8776-1c397de43491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>192e0d92-912b-4d31-be78-fc618c1d5d85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>74839ad3-6690-4cd7-aa86-131dc198c87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>0490de28-09ba-49df-9510-7835c0049be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aa08a9d6-8ecb-4850-a383-b84289009111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>9791f8c3-464d-418f-b1a0-9b9ffce37822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>936beee2-ce4a-4caf-94fc-26ea3bd10ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8b07786b-d226-4a13-a77b-51bacba317cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>08e68e51-4bd7-4544-89be-903471f7b91b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>55135c1b-74fd-43dc-8d41-88adcb0e3e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8955886f-79a7-44ef-a2dd-64a4eed8ea9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>0b59c5d6-bf18-458f-aae6-34fb265344da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>c89a3699-c431-4195-adb2-17f1e1d8dd8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b03c74e4-e8ce-456f-869b-1cd6cec28465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verifications</value>
      <webElementGuid>e482ee78-d3bf-4158-8b22-524451cefa97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications-container&quot;)/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>a73de3a0-04bb-4025-bd35-cfea430cbaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='verifications-container']/a/div/div</value>
      <webElementGuid>921cc357-5ade-4f03-b929-67c1b2f12dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[2]</value>
      <webElementGuid>50f8a056-3ab0-42e9-82a4-dfc8bfc98981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Services'])[1]/preceding::div[1]</value>
      <webElementGuid>3817a03b-27f7-4b83-9e45-589ffeba9c57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::div[3]</value>
      <webElementGuid>5b324d8b-f5a3-4ca1-a16f-870b24621ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verifications']/parent::*</value>
      <webElementGuid>b5d13ac1-fa6e-41be-bcee-fd1ba9452e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div</value>
      <webElementGuid>ebc56a8e-3652-4f6f-bdbe-14c666bb250a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Verifications' or . = 'Verifications')]</value>
      <webElementGuid>ef4875eb-33cc-4b33-9fef-6bbdcd465e0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
