<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Jan</name>
   <tag></tag>
   <elementGuidId>d219ff7b-084b-4008-9b05-fa72bf4be3b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dp__overlay_cell.dp__overlay_cell_pad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6276e7eb-7d9d-49d6-a8c8-c16223521139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__overlay_cell dp__overlay_cell_pad</value>
      <webElementGuid>adb1af22-8c9e-41f7-b28e-8a2e4d806b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jan</value>
      <webElementGuid>1a61b401-c8bd-4505-bd68-a43275d970e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper error pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[@class=&quot;dp__outer_menu_wrap&quot;]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__month_year_row&quot;]/div[@class=&quot;dp__month_year_wrap&quot;]/div[@class=&quot;dp__overlay&quot;]/div[@class=&quot;dp__overlay_container dp__container_flex&quot;]/div[@class=&quot;dp__overlay_row dp__flex_row&quot;]/div[@class=&quot;dp__overlay_col&quot;]/div[@class=&quot;dp__overlay_cell dp__overlay_cell_pad&quot;]</value>
      <webElementGuid>1b759ce3-d38b-4a00-be6f-edb8dd4bd02f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>44b95046-f6da-400d-a7bd-e3f0e41a1817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[24]</value>
      <webElementGuid>f79cd980-790b-46dc-af1a-e76653638da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jan']/parent::*</value>
      <webElementGuid>9d0872b3-26d8-4661-99a5-b36a7f6ceede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div/div</value>
      <webElementGuid>07751a52-be2e-43a4-8193-806b95ba7443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jan' or . = 'Jan')]</value>
      <webElementGuid>94fc7b93-29bf-4a9d-befa-9a61b23ebd2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
