<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1998</name>
   <tag></tag>
   <elementGuidId>267bf74b-79ed-43a3-916a-890426123d42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[3]/div/div[34]/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c7bf69c-495f-4880-9a95-ce8ebdc3b05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__overlay_cell dp__overlay_cell_pad</value>
      <webElementGuid>25fbc530-2c46-4004-9613-760fb438ff69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1998</value>
      <webElementGuid>e6d5fd04-1877-4243-bea6-6f35f8d9f250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper error pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[@class=&quot;dp__outer_menu_wrap&quot;]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__month_year_row&quot;]/div[@class=&quot;dp__month_year_wrap&quot;]/div[@class=&quot;dp__overlay&quot;]/div[@class=&quot;dp__overlay_container dp__container_block&quot;]/div[@class=&quot;dp__overlay_row dp__flex_row&quot;]/div[@class=&quot;dp__overlay_col&quot;]/div[@class=&quot;dp__overlay_cell dp__overlay_cell_pad&quot;]</value>
      <webElementGuid>d9aa1930-195d-4d2d-b7b0-b5c9a45210c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div[3]/div/div[34]/div[3]/div</value>
      <webElementGuid>7f1e3d8c-d76b-43b6-86a7-d85cbb03f42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[253]</value>
      <webElementGuid>a7eb1b2c-3461-4e99-93b0-54bd14fb88d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1998']/parent::*</value>
      <webElementGuid>27243d84-11a1-4be7-9bb4-f741704eb11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[34]/div[3]/div</value>
      <webElementGuid>fa586de7-7c89-4b0a-9e20-69d38dc0aa88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1998' or . = '1998')]</value>
      <webElementGuid>3b9ced53-8f9f-4e58-92ae-7736fb1cf8b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
