<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Services</name>
   <tag></tag>
   <elementGuidId>e9720a2f-e269-4c63-b898-bc9af479884a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='verifications']/li/a/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verifications > li > a.justify-content-between > div.d-flex.align-items-center > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43ce0ff3-e6ac-4329-8c2b-0851ef280dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>23b7ebc7-8833-4069-84e5-eb1c635bd17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>3021e9a3-06d2-46d7-aae1-4e79599b6e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>16477459-406f-48a8-904a-ad2670beddb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>bd093fee-a661-4195-8423-91106b033570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>1a82ad01-2666-4a86-9205-e1d7d828c235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2c0f0e94-1e04-4a12-a3f7-6299b6b24447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>65e9f899-0870-4c11-95bd-7127c8c3bd41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>2b2fbfce-c03b-4c0b-b1cb-048da1e0006b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>03618d67-5f42-428f-9d1c-75fb348ae632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>5678c977-19a9-4ed0-9476-2491f91abf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>ca287d49-5657-4649-be07-9947239aadfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d813e18-1338-4228-9de9-fd0ea7703bb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>4947f669-66ae-4db2-aa53-c77ac6052508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>1c28d161-8d5b-4e10-8d4b-1f69b936ef73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5f88e0b7-5a0e-4dfc-bf7f-a4e7ecae5ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>6bb3b36d-60a8-4a1e-9aed-b53c23c78a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>15986333-796f-4787-801f-9697781ff345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8d69b06c-aa9b-4622-bdd4-95af29688081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Services</value>
      <webElementGuid>c08a2c26-6aa5-4f97-b3f0-647cdc52d037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verifications&quot;)/li[1]/a[@class=&quot;justify-content-between&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/div[1]</value>
      <webElementGuid>b1fee46f-66f6-46de-9bfd-d1f850d483eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='verifications']/li/a/div/div</value>
      <webElementGuid>adcf4d7a-edda-4866-9b1d-c856741df1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifications'])[1]/following::div[2]</value>
      <webElementGuid>5416e595-eba0-4430-a398-c19f6a1f4683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[1]/following::div[4]</value>
      <webElementGuid>9fbede30-c05e-4284-9a6f-9b8530163996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reports'])[1]/preceding::div[1]</value>
      <webElementGuid>f2aab03c-21cf-482f-a755-7a68204fee39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Documentation'])[1]/preceding::div[3]</value>
      <webElementGuid>4e3f2475-c1cd-4fc0-9384-16a463286c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Services']/parent::*</value>
      <webElementGuid>dbaf8567-7b55-4dc1-9a01-0fa3ba8b5611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul/li/a/div/div</value>
      <webElementGuid>33bacccc-2b8b-40d4-8949-73b95c47ca2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Services' or . = 'Services')]</value>
      <webElementGuid>d1f1b6b4-42de-4a50-b178-4efa72826076</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
