<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_5</name>
   <tag></tag>
   <elementGuidId>fe617bec-bffa-4cfb-9bf7-17490d65fb92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[3]/div/div[7]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>806dfc72-4065-4393-b6d5-ded5f3e8faa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__cell_inner dp__pointer dp__date_hover</value>
      <webElementGuid>71fe4787-5354-4730-9cf9-0e651a188a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>3ba24db3-772a-4e2b-a9f9-a822cec58c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[@class=&quot;dp__outer_menu_wrap&quot;]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__calendar&quot;]/div[1]/div[@class=&quot;dp__calendar_wrap&quot;]/div[@class=&quot;dp__calendar&quot;]/div[@class=&quot;dp__calendar_row&quot;]/div[@class=&quot;dp__calendar_item&quot;]/div[@class=&quot;dp__cell_inner dp__pointer dp__date_hover&quot;]</value>
      <webElementGuid>db250635-8b0a-458f-965e-a29f81260b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div[3]/div/div[7]/div</value>
      <webElementGuid>17cb7709-1ae3-4d78-81b1-4aec3feeed97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select an Application to be billed for the request'])[1]/preceding::div[62]</value>
      <webElementGuid>439edf7b-8635-42ba-9581-4dc081a77dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application is required'])[1]/preceding::div[65]</value>
      <webElementGuid>e11da668-3e41-4f6e-8556-88684dea0aca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='5']/parent::*</value>
      <webElementGuid>632e5b24-c95e-4fc5-bcab-ac1ff956a6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[7]/div</value>
      <webElementGuid>cdfabcbf-44ca-4fba-b516-69412487ecbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '5' or . = '5')]</value>
      <webElementGuid>8768f597-9f6b-43ec-8bb3-89bd9271527e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
