<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nov</name>
   <tag></tag>
   <elementGuidId>4fd3516b-54f4-4bfa-a692-eea472b92e8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.dp__month_year_select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>40d54377-bcbd-40eb-8af6-5c413db96748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__month_year_select</value>
      <webElementGuid>505200c4-f637-4178-a2d2-f4f48a798470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2e96733d-3223-42bc-b1a2-2a18c9554f80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open months overlay</value>
      <webElementGuid>4b2d9b1a-87c2-4ab7-9d82-0ece2b419649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>132d3b84-3871-40ad-816a-0919394f119c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov</value>
      <webElementGuid>1cfc79a4-b01c-40f7-b8c6-4bd644630f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper error pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[@class=&quot;dp__outer_menu_wrap&quot;]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__month_year_row&quot;]/div[@class=&quot;dp__month_year_wrap&quot;]/div[@class=&quot;dp__month_year_select&quot;]</value>
      <webElementGuid>bc86fdae-f4b7-4686-a74b-8d883bb94e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2f2b138f-c3f2-4524-b065-a120d9191749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__month_year_select</value>
      <webElementGuid>53543110-3430-4b6a-8301-e36aa721db91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>732625af-1c2a-43df-bb07-4ab81c22c4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open months overlay</value>
      <webElementGuid>75ec08d3-40a4-449c-85a4-bda5f9de22b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6649793a-9d92-46e9-96e2-869633124fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nov</value>
      <webElementGuid>cb6e3cdd-bcd5-4cc2-b33c-d6ae70a3f89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[@class=&quot;dp__outer_menu_wrap&quot;]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__month_year_row&quot;]/div[@class=&quot;dp__month_year_wrap&quot;]/div[@class=&quot;dp__month_year_select&quot;]</value>
      <webElementGuid>43e2d3e7-f583-42b5-b0aa-107dd33247c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>98267882-af23-4c76-b0e5-716ae21d428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of Birth'])[1]/following::div[18]</value>
      <webElementGuid>62e6ecca-9696-4993-8bad-1aa866001b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lastname'])[1]/following::div[21]</value>
      <webElementGuid>f2779e2e-3593-4a21-a98c-dde30e4c6dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nov']/parent::*</value>
      <webElementGuid>f09f5565-a89c-4fed-8a21-b7f8bc5f39a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div</value>
      <webElementGuid>01adea84-b657-4803-a5b8-6ae5127b871a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Nov' or . = 'Nov')]</value>
      <webElementGuid>b907b1f1-712a-47b1-a797-0ff2f15a55d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
