<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Transactions</name>
   <tag></tag>
   <elementGuidId>86ed85ff-6053-4e0d-be53-69a8f418bc3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.text--lg.fw-bold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>411946ba-fe69-4dd4-aba8-8f88c2461681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--lg fw-bold</value>
      <webElementGuid>9ed5eb4f-a9a7-4c45-a23b-3acf16ac7411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
      <webElementGuid>eba991bb-6da8-4744-89d6-49f0e543bbd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;header px-0 flex-wrap mb-5&quot;]/div[@class=&quot;w-100 d-flex justify-content-between align-items-center flex-wrap&quot;]/div[@class=&quot;text--lg fw-bold&quot;]</value>
      <webElementGuid>4d81332c-0b8d-46e6-8c33-a8d4558b63b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div/div/div</value>
      <webElementGuid>c3aa63af-59f8-437e-8458-947a696d058e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/following::div[3]</value>
      <webElementGuid>a08e0c7a-c5bd-4cc5-a892-cb29aa53808f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Profile'])[1]/following::div[3]</value>
      <webElementGuid>5645e70f-3925-47f2-8c64-b8cec003d244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wallets'])[2]/preceding::div[2]</value>
      <webElementGuid>623d441b-444c-4d41-a15c-e69b3628c135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Collections'])[2]/preceding::div[2]</value>
      <webElementGuid>4b774eff-5753-4524-adcb-4181f01694dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div</value>
      <webElementGuid>a0407edf-b14f-4d28-b088-659e082ecb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Transactions' or . = 'Transactions')]</value>
      <webElementGuid>d64ea662-f75c-4f82-a58f-d5d0711fdf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
