<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_coreapp</name>
   <tag></tag>
   <elementGuidId>384c5fa3-0c81-43b3-837e-1af654addba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'option__list' and (text() = 'coreapp' or . = 'coreapp')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[text()=&quot;coreapp&quot;])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43973f9a-2c21-4cd6-84f1-ff9f82b594d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option__list</value>
      <webElementGuid>88336b38-33b1-4943-9340-a277cc2e3a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>coreapp</value>
      <webElementGuid>b8680177-f83e-4d55-b929-ee418cc6ad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;items&quot;]/div[@class=&quot;options&quot;]/div[@class=&quot;option__list&quot;]</value>
      <webElementGuid>7df98c6e-c6ad-40be-8049-f3a70c010fbc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouch-notification-app'])[2]/following::div[1]</value>
      <webElementGuid>13d68b15-cd4f-4b2a-b464-a0207de60676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouchapp2'])[2]/following::div[2]</value>
      <webElementGuid>0f4d6e75-250d-4488-a129-732fca2978c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all-identity'])[2]/preceding::div[1]</value>
      <webElementGuid>537f4cfa-1a23-4047-8fbc-6983e3bc4fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev-test'])[2]/preceding::div[2]</value>
      <webElementGuid>2d58c209-87ae-4aa6-886d-f99036daca60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]</value>
      <webElementGuid>87a66dcd-f763-4ed1-97d5-2539e4c03cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'coreapp' or . = 'coreapp')]</value>
      <webElementGuid>b2de850b-91c3-4dec-9f0d-716a8cb240b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouch-notification-app'])[1]/following::div[1]</value>
      <webElementGuid>9325663e-9b59-4a87-98bf-986b0733160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bluintouchapp2'])[1]/following::div[2]</value>
      <webElementGuid>7b239a4f-31e4-4bf4-aae1-a148a62fa5ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='all-identity'])[1]/preceding::div[1]</value>
      <webElementGuid>3a4a73b0-0fb3-470a-a277-d89ee2d7d0ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dev-test'])[1]/preceding::div[2]</value>
      <webElementGuid>896ed03b-ff76-4958-b49f-384e2ea30f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='coreapp']/parent::*</value>
      <webElementGuid>5038b2bd-2ff9-4d8a-a4f4-2523006b45f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]</value>
      <webElementGuid>4d347d56-f667-4ef1-b7fe-3bbfe666a25e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
