<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_9011340763</name>
   <tag></tag>
   <elementGuidId>0ca15b68-6ff0-48da-9d3b-83f75acf9964</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.text--primary.m-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-form']/div/div[2]/div/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b6d9bb0f-cb3d-489d-a633-0f972b30b0da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text--primary m-0</value>
      <webElementGuid>3ad0869b-b78e-42b5-9217-04b182610064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>9011340763</value>
      <webElementGuid>98a60fb3-0262-46d1-93e4-43e6ff830e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-form&quot;)/div[@class=&quot;g-bold text--gray&quot;]/div[@class=&quot;mt-5&quot;]/div[@class=&quot;bg-light rounded w-100 px-3 py-4&quot;]/div[@class=&quot;flex__between&quot;]/h1[@class=&quot;text--primary m-0&quot;]</value>
      <webElementGuid>80386c43-0e0e-456f-b99c-d7e6ae20fa6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_BluSalt/iframe_Failed_vue-iframes</value>
      <webElementGuid>bcc8e0c3-85e1-4bed-8488-136badb4d112</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-form']/div/div[2]/div/div/h1</value>
      <webElementGuid>cf48bf21-225f-4f02-bfeb-a1000639f024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NGN 1,000.00'])[2]/following::h1[1]</value>
      <webElementGuid>e875babe-f66e-452a-ae45-b2418de930ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/preceding::h1[1]</value>
      <webElementGuid>56e687cc-49e5-483b-a522-0b33c5f58c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use this account for this transaction only. Expires in'])[1]/preceding::h1[1]</value>
      <webElementGuid>7e9a6628-fdb5-40ec-88eb-267a6d9fe381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='9011340763']/parent::*</value>
      <webElementGuid>337c7279-a1b8-44b0-b87f-b6eb06541a27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>9a32f9dc-5dd3-48a7-b135-ee50b3f0e6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = '9011340763' or . = '9011340763')]</value>
      <webElementGuid>43a12b4b-39ef-48ce-ac77-b790161fb59e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
