<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Failed_vue-iframes</name>
   <tag></tag>
   <elementGuidId>60294e9c-618b-48b2-b59a-8644142d4c30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vue-iframes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='vue-iframes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>be451073-bb7b-4d4b-916f-3b0371d2f566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vue-iframes</value>
      <webElementGuid>9667bc6c-079f-4ed3-8a47-5d492592b49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb7e0d0d-6318-4d82-bc37-2fa65a0b6cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://checkout.blusalt.net/TCH-u218bwZFG</value>
      <webElementGuid>aa3ca6b5-4a6a-4389-9cfe-1076e18b9395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>crossorigin</name>
      <type>Main</type>
      <value>anonymous</value>
      <webElementGuid>d9c85a62-ef6d-464a-abfb-bfb2b360b241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vue-iframes</value>
      <webElementGuid>d553bb80-aa33-4502-ab80-0e8e06285fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>camera *; geolocation *; microphone *; autoplay *</value>
      <webElementGuid>2431a7a7-3764-4d79-8d79-4acb10bc303c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_parent</value>
      <webElementGuid>40fd1e04-9dbb-4834-ad21-a7d6e1604c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vue-iframes&quot;)</value>
      <webElementGuid>33f5c347-dee5-4024-b97b-ed17d285107a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='vue-iframes']</value>
      <webElementGuid>ecb7ec32-9042-439b-a53a-378edd9081e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/div[2]/iframe</value>
      <webElementGuid>e8762dc2-9854-411d-9499-adecc39ea948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>51d0bec0-d50f-4d41-9e99-e7ab5301b8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'vue-iframes' and @src = 'https://checkout.blusalt.net/TCH-u218bwZFG' and @name = 'vue-iframes']</value>
      <webElementGuid>d9d85ec2-f95b-4d7e-be64-53e5246cd9a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
