<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Close_mb-5</name>
   <tag></tag>
   <elementGuidId>47906a72-61d0-4958-a849-fd03939c3e93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>x	</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mb-5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>6cee42e9-1a0b-44eb-8c1e-9bef56696ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-5</value>
      <webElementGuid>5b40ac15-d48d-434c-ab7d-65a7bfe36e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://staging-api.blusalt.net/_/u13Kr6Oue</value>
      <webElementGuid>b267737d-44f5-4abb-ac43-899b579a1e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging-api.blusalt.net/_/u13Kr6Oue</value>
      <webElementGuid>186450aa-66ca-4f65-b4d7-eaca90886d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lazy</name>
      <type>Main</type>
      <value>loaded</value>
      <webElementGuid>696efbc7-6f57-4b32-8833-8b248ac3e1fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/div[1]/img[@class=&quot;mb-5&quot;]</value>
      <webElementGuid>ddc1c1a9-3933-4e5f-bdd5-b18aadbca0f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/div/img</value>
      <webElementGuid>ce850db8-bec6-4fcb-99e8-db8eed2e13f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://staging-api.blusalt.net/_/u13Kr6Oue')]</value>
      <webElementGuid>318fbadd-a817-4b4a-a973-c00571135345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/img</value>
      <webElementGuid>7da230f4-dae0-44c0-9c2f-31f169976a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging-api.blusalt.net/_/u13Kr6Oue']</value>
      <webElementGuid>7b7ee853-226f-4821-bf99-3989e34e70cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
