<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Passport Number_passport_number</name>
   <tag></tag>
   <elementGuidId>9b132438-7bbb-4176-86cd-c87bd6b5ff7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passport_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#passport_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>de6faafe-24f0-4a20-8c3e-ea4d3758a35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100</value>
      <webElementGuid>b81b2c43-6c01-4270-9349-16c178479335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>243d75e4-d668-43b5-8d74-e6d4d2e02ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passport_number</value>
      <webElementGuid>2c968d41-b8c3-45fc-8784-6f6ce66e30e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passport_number</value>
      <webElementGuid>67f34779-1d55-4d37-b0ec-dfe8e06e3ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Passport Number</value>
      <webElementGuid>7d5a9450-894a-41e7-9c28-f1eb03b152e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7221ea49-e081-4a86-997a-64bd4c296191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>499cc617-4711-4111-b5cf-1c8cf0a29241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passport_number&quot;)</value>
      <webElementGuid>f0473a9b-a784-4ab2-b16b-0c93dc1df094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passport_number']</value>
      <webElementGuid>ae51d686-983c-4832-91bb-8a553b2058ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div/div/div/input</value>
      <webElementGuid>84c6a378-bbe5-481b-8c05-966ba11ca4da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>db50a774-c24e-4136-9c0e-3d9c7e28b63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'passport_number' and @name = 'passport_number' and @placeholder = 'Enter Passport Number']</value>
      <webElementGuid>253a3832-fc95-410e-83a5-497dffb9c79d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
