<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of Birth_dob</name>
   <tag></tag>
   <elementGuidId>16630bc6-5a68-46ae-83d8-6d64667654d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dob']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dob&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c2ac383-866c-4052-ba97-e419ecc38726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dob</value>
      <webElementGuid>2d908c86-ea4c-4a01-99ca-11d639cfb2b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_focus dp__input_reg</value>
      <webElementGuid>b4bbc1cb-abef-4e9b-8973-ceca9c3768ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>5b53b70b-a750-47f9-b3ec-f2ce014350d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>d2f3ae9c-a16d-487c-a8cd-279508b4c5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4c34b73b-5bc9-4cc9-b4ce-05c5714e2c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id=&quot;app&quot;]/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-lg-6&quot;]/div[@class=&quot;form-group date-input--bordered&quot;]/div[@class=&quot;input-container-wrapper date-input&quot;]/div[@class=&quot;d-flex align-items-center input-wrapper error pad&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[1]/div[@class=&quot;dp__input_wrap&quot;]/input[@class=&quot;dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_focus dp__input_reg&quot;]</value>
      <webElementGuid>67b83e40-adc5-48b1-823a-c2e9597b9d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dob']</value>
      <webElementGuid>95640a40-1b62-497e-9c93-482d28cc1ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/form/div[2]/div[5]/div/div/div/div/div/div/input</value>
      <webElementGuid>1d1e14ca-719e-426d-991a-ecfadd668e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/input</value>
      <webElementGuid>3acd84ca-a275-4f5b-9f48-07de3d0b8810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dob' and @placeholder = 'Date of Birth']</value>
      <webElementGuid>176e0c4a-2528-4b3f-ab74-0b1eff1cbc09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
