<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Drivers License</name>
   <tag></tag>
   <elementGuidId>8352e137-85b9-4dbb-bad4-bce80cb5a2e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nigerian-services']/li[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d9c64451-d083-4273-adb5-5faba715b308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Drivers License</value>
      <webElementGuid>3e53029c-dbf1-4fa8-aaf6-fe18edd6b4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nigerian-services&quot;)/li[13]</value>
      <webElementGuid>3b30e8a8-e5ec-4fc3-90b9-c501a93c0631</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nigerian-services']/li[13]</value>
      <webElementGuid>b0a0e19b-9296-4e9c-ac49-65e76a4ab6df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='International Passport'])[1]/following::li[1]</value>
      <webElementGuid>3e3e3973-68eb-4dcf-9b59-31ba313e327e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VNIN'])[1]/following::li[2]</value>
      <webElementGuid>3982303c-dafa-4853-ae72-47815927b12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IDENTITY (GHANA)'])[1]/preceding::li[1]</value>
      <webElementGuid>f8d83388-fac1-4ecd-ad56-1f1785f7da81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[2]/preceding::li[1]</value>
      <webElementGuid>102fb169-4aff-41ba-a6de-7c9982b60d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Drivers License']/parent::*</value>
      <webElementGuid>4de60c04-dbda-4235-82ac-11cc73a05045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[13]</value>
      <webElementGuid>8ca3bfb6-8059-491e-91d8-1fd521603e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Drivers License' or . = 'Drivers License')]</value>
      <webElementGuid>39bf429f-c583-42dd-9a36-af2ac66a2f42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
