<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_iBVN</name>
   <tag></tag>
   <elementGuidId>a24ec930-d8fd-435e-8c12-c91d0d7e12e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'iBVN' or . = 'iBVN')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nigerian-services']/li[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ea4c2490-4a79-4de2-8baa-b533a188807d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>iBVN</value>
      <webElementGuid>3c72983f-6937-48a8-8d3d-07c2a0cd4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nigerian-services&quot;)/li[2]</value>
      <webElementGuid>735fae91-26bf-467e-9bad-0a64d42c69ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nigerian-services']/li[2]</value>
      <webElementGuid>9cd62e23-bb38-48f6-a71a-f71b6d45085b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BVN'])[1]/following::li[1]</value>
      <webElementGuid>8fe4084d-8a15-4657-8add-1320196fafb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::li[2]</value>
      <webElementGuid>0c603a1e-eb5b-4d1b-9bc6-0680b6fbf168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pBVN'])[1]/preceding::li[1]</value>
      <webElementGuid>435e204f-b061-4f74-a13a-1ba2c36e35b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk BVN'])[1]/preceding::li[2]</value>
      <webElementGuid>7e77714f-8292-4b80-a0e1-9057551063d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='iBVN']/parent::*</value>
      <webElementGuid>0ea94675-cbae-4fbe-ac5d-941c66a44d71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/li[2]</value>
      <webElementGuid>79a32313-b607-42b0-a76d-5bf5accc0d88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'iBVN' or . = 'iBVN')]</value>
      <webElementGuid>b0c231c8-5e83-4071-85a7-7cb4954c6f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
