<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Lagos</name>
   <tag></tag>
   <elementGuidId>f5d30f14-53b6-4818-815f-0de61734d12a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs2__option-0</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'vs2__option-0' and (text() = 'Lagos' or . = 'Lagos')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs2__option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ab359df1-3dcd-49e9-82aa-c24fa0f7be27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs2__option-0</value>
      <webElementGuid>be2b406d-95ee-40a7-91e0-2e610a97e816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>95ff8700-1b46-49d2-a3cb-012893bda15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>7dc907df-b8e2-43db-830a-9470d97541e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6f29fcb0-3ab2-4e81-8aba-5f5b7df8d6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lagos</value>
      <webElementGuid>71d8771c-a6bf-4b4e-9c94-662d629ee614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs2__option-0&quot;)</value>
      <webElementGuid>5a508a34-aa15-407f-9750-680ebdf4e6f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs2__option-0']</value>
      <webElementGuid>4a545db3-e142-4ad3-8894-04ddb7b5e905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs2__listbox']/li</value>
      <webElementGuid>88a39f4e-96e8-4329-a812-ce4a130e8ef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[1]</value>
      <webElementGuid>dfd6e40d-eab1-47cb-9d7f-e92d615b55ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State of Registration'])[1]/following::li[1]</value>
      <webElementGuid>22403b73-9b2b-4231-b387-e10353f32b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State is required'])[1]/preceding::li[2]</value>
      <webElementGuid>13426971-69cf-4d3c-8190-98df5b36a1cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lagos']/parent::*</value>
      <webElementGuid>604cb972-87b9-41b3-8746-71f7f6faf939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li</value>
      <webElementGuid>c159e43f-2201-4842-9cac-e21b8fdd5391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs2__option-0' and (text() = 'Lagos' or . = 'Lagos')]</value>
      <webElementGuid>15c00a4e-5f6c-487d-88ca-962fe7c59f36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
