<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PVC</name>
   <tag></tag>
   <elementGuidId>f87833a0-e2e7-47d3-8729-255f036f5a0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nigerian-services']/li[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>8298abfe-b26b-4e3c-b4a0-b1dd8544356a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PVC</value>
      <webElementGuid>d42b56da-fd30-4e79-84d5-df1c5bf81290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nigerian-services&quot;)/li[5]</value>
      <webElementGuid>dbe6ae72-bef9-4cf9-aeb7-b8602d649c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nigerian-services']/li[5]</value>
      <webElementGuid>1acabbff-788d-4b91-a1d6-c4b5592f2f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk BVN'])[1]/following::li[1]</value>
      <webElementGuid>48cfb60f-decc-489f-b5d1-c0ea246f407c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pBVN'])[1]/following::li[2]</value>
      <webElementGuid>7e85c27b-5eb3-4f51-a61a-1af577494293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIN'])[1]/preceding::li[1]</value>
      <webElementGuid>690ab5b1-d730-44a0-9326-a5108fe9084f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk NIN'])[1]/preceding::li[2]</value>
      <webElementGuid>d336ee5a-e106-4f9f-a0ca-72bb886fb531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PVC']/parent::*</value>
      <webElementGuid>af8689da-061c-47b2-a2e5-e2105c4ccf79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[5]</value>
      <webElementGuid>76f02325-2304-4cb9-9a29-e87623384406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'PVC' or . = 'PVC')]</value>
      <webElementGuid>1a48e2bb-7732-42b2-a3ac-3eeb817d200d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
