<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_PNIN</name>
   <tag></tag>
   <elementGuidId>b12acc0a-0961-49e9-8c6e-dcf056218e24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nigerian-services']/li[8]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>656dbbe3-3a4a-4d0d-8fd0-8b89d7ee7ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PNIN</value>
      <webElementGuid>12f3d7e6-d816-480a-9244-12dad882b2cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nigerian-services&quot;)/li[8]</value>
      <webElementGuid>28749601-843a-4665-a870-34bd4cebe8cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nigerian-services']/li[8]</value>
      <webElementGuid>b51f3639-5f5a-4e2e-a33c-e1d8e0271f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk NIN'])[1]/following::li[1]</value>
      <webElementGuid>818dd29d-73ef-4356-af36-5a7414b17078</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIN'])[1]/following::li[2]</value>
      <webElementGuid>4c0fe927-20ea-4bf9-9897-d894b2843d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PNIN Basic'])[1]/preceding::li[1]</value>
      <webElementGuid>499f3b45-0449-4f88-b7ef-db40a11ceca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulk PNIN Basic'])[1]/preceding::li[2]</value>
      <webElementGuid>b12fb9ae-d643-45ea-9799-bfb5ea4c7c14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PNIN']/parent::*</value>
      <webElementGuid>57df3fb1-5009-4e79-b681-e75fb2247d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[8]</value>
      <webElementGuid>4975ab70-023e-4c84-be20-9f6f09133689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'PNIN' or . = 'PNIN')]</value>
      <webElementGuid>2f9e1f6e-f1d6-4c00-95ea-593cf597b64a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
