<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_V2</name>
   <tag></tag>
   <elementGuidId>69b2b96f-356e-4741-b703-ad63273e21c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vs2__option-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'V2' or . = 'V2')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='vs2__option-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9dbe62ec-8c0d-4ca3-9687-b792c0647399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vs2__option-1</value>
      <webElementGuid>ca5b58df-8248-454b-bf08-a6889fca1454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>8d261857-0b97-47fc-b02f-fa1264565595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vs__dropdown-option vs__dropdown-option--highlight</value>
      <webElementGuid>b8eea597-5cc7-4d98-bf21-ae12371d2540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cd00ce18-18b6-4561-909c-f7501636d366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>V2</value>
      <webElementGuid>202b97b3-5653-4be7-9ef5-6c104745a2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vs2__option-1&quot;)</value>
      <webElementGuid>61e7c7bb-795d-4981-b66c-2209e1604914</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs2__option-1']</value>
      <webElementGuid>90ef2e0b-55bb-42a6-a708-6e97505fe486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs2__listbox']/li[2]</value>
      <webElementGuid>e10ae432-86a1-422e-a12f-32ad3a92c611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::li[2]</value>
      <webElementGuid>8d8b8068-be84-4e34-969d-c3d616677ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='API Version is required'])[1]/preceding::li[1]</value>
      <webElementGuid>38378374-1300-4f7b-9c33-211e968cd713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::li[1]</value>
      <webElementGuid>32105019-7534-4e35-82f8-1914752d2f8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='V2']/parent::*</value>
      <webElementGuid>7ad1ec1c-1d08-441b-baf3-14ec9009506c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/ul/li[2]</value>
      <webElementGuid>ac94ddce-404a-46b5-9f7e-6732cfbd4548</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs2__option-1' and (text() = 'V2' or . = 'V2')]</value>
      <webElementGuid>21515932-5f98-4b85-9986-c86e9b3be818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='vs1__option-1']</value>
      <webElementGuid>7f37f936-7de8-4669-aa60-3c3828f35ef7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='vs1__listbox']/li[2]</value>
      <webElementGuid>14847eb2-00cb-4a1f-bb66-868acf938304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'vs1__option-1' and (text() = 'V2' or . = 'V2')]</value>
      <webElementGuid>5e49f2d7-56e1-487f-a856-0e8b3c31d493</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
