<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_OBALOLUWA</name>
   <tag></tag>
   <elementGuidId>236ca9b3-132c-40bf-a024-52d3d8acbab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/div/div[2]/section/p[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>528c8660-e3c7-4191-81e6-9b552f5c1269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-0</value>
      <webElementGuid>b9b271b5-b77b-4e37-a582-c32d170c29e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OBALOLUWA</value>
      <webElementGuid>77c422a4-a951-4efc-a977-15216a4bf350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/section[@class=&quot;dashboard-container&quot;]/main[@class=&quot;main p-4 p-md-5&quot;]/section[@class=&quot;section--container section--margin&quot;]/div[@class=&quot;verification-layout&quot;]/div[@class=&quot;verification-main&quot;]/div[@class=&quot;mb-5&quot;]/div[1]/div[@class=&quot;info__section&quot;]/section[@class=&quot;justify-content-between border-bottom mb-4&quot;]/p[@class=&quot;mb-0&quot;]</value>
      <webElementGuid>89f5f0c9-4cc5-4da9-b6d0-d18e4ece9566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/section/main/section/div[2]/div[2]/div/div/div[2]/section/p[2]</value>
      <webElementGuid>0e4fa40f-c886-4158-8cea-fb1779f1d74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::p[2]</value>
      <webElementGuid>58fe3066-90e8-443b-8b41-949283240abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID'])[1]/following::p[4]</value>
      <webElementGuid>b192adfa-780e-45f1-acd0-010bb51a7bbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Endpoint'])[1]/preceding::p[25]</value>
      <webElementGuid>85e60094-1865-4deb-8a94-9b00338477ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('', '&quot;', 'POST : https://staging-api.blusalt.net/v2/IdentityVerification/NIP', '&quot;', '')])[1]/preceding::p[25]</value>
      <webElementGuid>150e1e4a-482b-4328-b38f-5c5979c0a778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OBALOLUWA']/parent::*</value>
      <webElementGuid>f92236e5-aa13-4daf-9745-ab4290e30e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/p[2]</value>
      <webElementGuid>703a8d22-86ce-40d1-9ebc-6bd4b648a6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'OBALOLUWA' or . = 'OBALOLUWA')]</value>
      <webElementGuid>08191ccc-b06d-439f-b916-2e8f0d8d3e51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
