<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Payment Link Created Successfully</name>
   <tag></tag>
   <elementGuidId>b89c0471-a719-4135-b17b-c7337bd9d0d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.heading-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal--main-section']/div/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>dcd10821-18b0-46ea-8162-62ad8a7d3150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-1</value>
      <webElementGuid>89ee55f5-34b8-405e-b1ed-7400425c20d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Payment Link Created Successfully</value>
      <webElementGuid>dfbba222-0a79-4a0c-b2c0-f4c829131b79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal--main-section&quot;)/div[@class=&quot;text-center&quot;]/div[1]/div[@class=&quot;col-12 col-sm-11 m-auto&quot;]/p[@class=&quot;heading-1&quot;]</value>
      <webElementGuid>03cf62a4-cc45-4926-aa30-1cc0406c0d1b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal--main-section']/div/div/div/p</value>
      <webElementGuid>896df099-1dac-4bb7-9be3-2ab00b36c29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Request for funds for your existing wallets'])[1]/following::p[1]</value>
      <webElementGuid>d8999da2-6ee9-47bd-bc92-931527b2053e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Link'])[1]/preceding::p[2]</value>
      <webElementGuid>00ef9409-fd7a-4fa6-8977-2f41b7ec6876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy'])[1]/preceding::p[2]</value>
      <webElementGuid>538d244a-38c4-4a18-b2a5-47ec1ce0612a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Link Created Successfully']/parent::*</value>
      <webElementGuid>9be41b67-47d4-4363-a2ae-8156db4a1ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div/div/p</value>
      <webElementGuid>b64c88f2-da77-4fcf-99ab-5c9d298b2d1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Payment Link Created Successfully' or . = 'Payment Link Created Successfully')]</value>
      <webElementGuid>c66d49cc-08cb-4164-b4b2-b2313992e78c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
