<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Successful</name>
   <tag></tag>
   <elementGuidId>d7a8fce1-7077-4cea-8c3b-f0a63a48459d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal--main-section']/div/div/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-12.col-sm-11.m-auto > p.heading-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>4fb6af6d-e12a-4d82-8fa6-ccd30def49cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading-1</value>
      <webElementGuid>9221086b-ef53-47d1-afdf-9dd40c28e6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successful</value>
      <webElementGuid>dc220dfa-ea80-4baa-a759-d4c9779e10d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal--main-section&quot;)/div[@class=&quot;text-center&quot;]/div[1]/div[@class=&quot;col-12 col-sm-11 m-auto&quot;]/p[@class=&quot;heading-1&quot;]</value>
      <webElementGuid>8667197f-4103-49f1-8a3e-588709788af4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal--main-section']/div/div/div/p</value>
      <webElementGuid>fa7bb811-34d1-4687-aa0b-8dbf016e9f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[2]/following::p[1]</value>
      <webElementGuid>8fcd6806-0ff8-4e5f-b68e-5c0af32e1ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::p[2]</value>
      <webElementGuid>ce679e8e-7b73-42c5-8068-3f7b854d8d9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Successful']/parent::*</value>
      <webElementGuid>aa6f49da-503a-436f-a869-8bad6dc4e71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/p</value>
      <webElementGuid>647a705d-8bd8-46f4-b49c-d59ee12e9aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Successful' or . = 'Successful')]</value>
      <webElementGuid>6051faae-88d2-4028-8cee-5ad1c215ead0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
